create table if not exists public.analises_credito (
    id bigint generated by default as identity primary key,
    cnpj text,
    receita_liquida_anual numeric(15, 2) not null,
    liquidez_corrente numeric(10, 2) not null,
    margem_liquida numeric(10, 2) not null,
    endividamento_geral numeric(10, 2) not null,
    score integer not null,
    classificacao_risco text not null,
    status_decisao text not null,
    limite_sugerido numeric(15, 2) not null,
    created_at timestamptz not null default now()
);

alter table public.analises_credito enable row level security;

drop policy if exists "service role can manage credit analyses" on public.analises_credito;

create policy "service role can manage credit analyses"
on public.analises_credito
for all
to service_role
using (true)
with check (true);
